<a href="https://colab.research.google.com/github/Shivieo/featureEng_con/blob/feature/Feature_Engineering_concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1. What is parameter?
# In feature engineering, parameters are learned from the data during training process. There are three ways to do parameters:
#1. Binning - When binning a numerical feature, the number of bins and the width of each bin are parameters.
#2. Scaling - Scaling is done on categorical data to get the numerical values. Normalization, Standardization, One hot encoding
#3. Principal Component Analysis (PCA) - It is use to reduce dimensionality of datasets.

In [ ]:
#2. What is correlation? What does negative correlation mean?
# Correlation shows the relation among variables(columns). Using standard deviation and variance, We get correlation. The correaltion values lie between -1 to 1.
# Negative correlation means there is no any link between two column or variable.

In [ ]:
#3. Define Machine Learning. What are the main components in Machine Learning?
# Machine Learning is a subfield of Artificial Intelligence that focuses on learning data for the model or machine like by using ML algorithms, one can
# identify patterns, measure prediction and improve the performance of model means more data more experienced more improved.
# Main Components of Machine Learning:-
# a. Data: Data is the foundation of Machine Learning system. It is used to train the model and evaluate its performance. The quality, quantity and relevance
# of data is crucial for building effective ML model.
# b. Algorithm: It is the core of ML system. An algorithm is a set of rules and statistical techniques used to learn patterns from the data.
# Supervised Learning, Unsupervised Learning and Reinforcement Learning.
# c. Model: The model represents learned patterns and relationships from the data. It is used to make prediction on new data.
# d. Evaluation: This process is used to evaluate the perfomance of model that how well model works.
# e. Features: These are the individual measurable properties or characteristics of the data. Feature engineering involves selecting, transforming, and creating relevant
# features to improve model performance.

In [ ]:
#4. How does loss value help in determining whether the model is good or not?
# Loss value determines how well model is performing means lower the loss value, lower the difference between actual and predicted variable, better the model is
# But very few loss values leads overfitting. Overfitting is also impact model performance.


In [ ]:
#5. What are continuous and categorical variables?
# continuous variables are those variables that are in a given range. It can often be in decimal and fractional values. eg. height, weight, time, temperature etc
# Categorical variables are variable that are in object or string type. They are non numeric. Eg. color, blood group, education level etc


In [ ]:
#6. How do we handle categorical variables in Machine Learning? What are the common techniques?
# Most machine algorithm works with numerical algorithm. So, we convert categorical variable into numerical variable. Common techinques :
# 1. One_hot_encoding - Creates new binary columns for each unique category in the original variable. If a data point belongs to a specific
#category, the corresponding column gets a '1', and all other category columns get a '0'.
# 2. Label Encoding(Ordinal Encoding): Assigns a unique integer to each category.
# 3. Target Encoding (Mean Encoding): Replaces each category with the mean of the target variable for that category.
# 4. Binary Encoding: First, the categories are assigned integers as in label encoding. Then, those integers are converted into binary code.
# Each binary digit becomes a new column.
# 5. Frequency Encoding: Replaces each category with its frequency (or count) in the dataset.

In [ ]:
#7. What do you mean by training and testing a dataset?
# Training - During Training process, our model learns patterns, relationship and trends from the data.
# Testing - This is the process done on test data which is unseen to the model and here we see that how well model is performing on unseen data which
# is a part of the dataset from where trained and test splited.

In [ ]:
#8. What is sklearn.preprocessing?
# sklearn.preprocessing is a module of scikit-learn (sklearn) library in python that provides a variety of tools for preprocesssing data before it is used
# for Machine Learning Models.
#key features of sklearn.preprocessing
#Standard(scaling) - This standardizes the features by removing the mean and scaling to unit variance(mean=0, std=1)
#Normalization - Normalizes samples individually to have unit norm.
#Encoding Categorical features - One Hot Encoding, Label encoder, Ordinal encoder

In [ ]:
#9. What is a Test set?
# A test set is unseen set of data that is extracted from the dataset from which most of the data used for training and rest kept as test data. It is used
# to see how well the model is performing on test data.

In [5]:
#10. How do we split data for model fitting (training and testing) in Python? How do you approach a Machine Learning problem?
# from sklearn.model_selection import train_test_split;
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42);
# Here's a general framework for approaching a machine learning problem:

# 1. Define the Problem

# Clearly state the objective: What are you trying to predict or achieve? (e.g., predict customer churn, classify images, forecast sales)
# Identify the type of problem: Is it a classification, regression, clustering, or another type of problem?
# Define evaluation metrics: How will you measure the success of your model? (e.g., accuracy, precision, recall, F1-score for classification; mean squared error, R-squared for regression)
# 2. Data Collection and Preparation

# Gather data: Collect relevant data from various sources.
# Data cleaning: Handle missing values, outliers, and inconsistencies.
# Exploratory Data Analysis (EDA):
# Understand the data through visualizations and summary statistics.
# Identify patterns, relationships, and potential issues.
# Feature engineering: Create new features from existing ones to improve model performance.
# Data preprocessing: Scale or normalize numerical features, encode categorical features.
# 3. Model Selection

# Choose appropriate algorithms: Select algorithms that are suitable for the problem type and data characteristics.
# Consider model complexity: Balance model complexity with the risk of overfitting.
# 4. Model Training and Evaluation

# Split the data: Use train_test_split or cross-validation techniques.
# Train the model: Fit the chosen algorithm on the training data.
# Tune hyperparameters: Optimize model parameters using techniques like grid search or random search.
# Evaluate the model: Assess the model's performance on the test set using the chosen evaluation metrics.
# 5. Deployment and Monitoring

# Deploy the model: Integrate the model into a production system.
# Monitor performance: Continuously track the model's performance and retrain it as needed.

In [ ]:
#11. Why do we have to perform EDA before fitting a model to the data?
# Make informed decisions: About data preprocessing, feature engineering, and model selection.
# Improve model performance: By addressing data quality issues and selecting appropriate models.
# Avoid costly mistakes: By identifying potential problems early on.

In [6]:
#12. What is correlation?
# Correlation shows the relation among variables(columns). Using standard deviation and variance, We get correlation. The correaltion values lie between -1 to 1.
# Negative correlation means there is no any link between two column or variable.

In [ ]:
#13. What does negative correlation mean?
# Negative correlation means there is no any link between two column or variable.

In [7]:
#14.How can you find correlation between variables in Python?
# to find correlation in python
import pandas as pd
import numpy as np

# Sample DataFrame (replace with your data)
data = {'A': [1, 2, 3, 4, 5],
        'B': [2, 4, 1, 3, 5],
        'C': [5, 4, 3, 2, 1],
        'D': [10, 12, 11, 13, 15]}
df = pd.DataFrame(data)

# Calculate the correlation matrix (Pearson by default)
correlation_matrix = df.corr()
print("Correlation Matrix:\n", correlation_matrix)

# Correlation between two specific columns
correlation_AB = df['A'].corr(df['B'])
print("\nCorrelation between A and B:", correlation_AB)

# Using NumPy's corrcoef (for Pearson correlation)
correlation_matrix_np = np.corrcoef(df.values, rowvar=False) #rowvar=False is crucial if columns are variables
print("\nCorrelation Matrix (NumPy):\n", correlation_matrix_np)

Correlation Matrix:
           A         B         C         D
A  1.000000  0.500000 -1.000000  0.904194
B  0.500000  1.000000 -0.500000  0.821995
C -1.000000 -0.500000  1.000000 -0.904194
D  0.904194  0.821995 -0.904194  1.000000

Correlation between A and B: 0.49999999999999994

Correlation Matrix (NumPy):
 [[ 1.          0.5        -1.          0.90419443]
 [ 0.5         1.         -0.5         0.82199494]
 [-1.         -0.5         1.         -0.90419443]
 [ 0.90419443  0.82199494 -0.90419443  1.        ]]


In [9]:
#15. What is causation? Explain difference between correlation and causation with an example.
# Causation indicates that one event is the direct result of another event. It means that a change in one variable causes a change in another variable.
# Correlation, on the other hand, simply indicates that two variables are related or tend to move together. It doesn't necessarily mean that one causes the other.

# The key difference is the presence of a cause-and-effect relationship. Causation implies a direct link where a change in one variable leads to a change in
# the other. Correlation only suggests an association or pattern between variables, without implying a direct cause.

In [ ]:
#16. What is an Optimizer? What are different types of optimizers? Explain each with an example
# In machine learning, an optimizer is an algorithm or method used to adjust the parameters of a model (e.g., weights and biases in a neural network) in order
# to minimize a loss function. The loss function measures how well the model is performing on the training data. The goal of the optimizer is to find the set
# of parameters that minimizes this loss, effectively improving the model's accuracy.
# Here are some common types of optimizers:

# 1. Gradient Descent (GD)

# This is the most fundamental optimization algorithm. It works by iteratively adjusting the parameters in the direction of the steepest descent of the loss function. The "gradient" indicates the direction of the steepest ascent, so we move in the opposite direction to minimize the loss.

# How it works: GD calculates the gradient of the loss function with respect to the parameters. It then updates the parameters by taking a small step in the opposite direction of the gradient. The size of the step is determined by the learning rate.
# Example (Conceptual): Imagine you're standing on a hill and want to get to the bottom. You look around and find the direction where the ground slopes down most steeply. You take a step in that direction. You repeat this process until you reach the bottom.
# Variants:
# Batch Gradient Descent: Calculates the gradient using the entire training dataset. It's computationally expensive for large datasets.
# Stochastic Gradient Descent (SGD): Calculates the gradient using only one randomly chosen training example at a time. It's much faster than batch GD but can be noisy.
# Mini-Batch Gradient Descent: Calculates the gradient using a small batch of training examples. It's a compromise between batch GD and SGD, offering a good balance between speed and stability.
# 2. Momentum

# Momentum helps to accelerate SGD in the relevant direction and dampens oscillations. It does this by adding a fraction of the previous update to the current update.

# How it works: Momentum keeps track of an exponentially decaying average of past gradients. This "momentum" helps the optimizer to overcome small local minima and navigate through plateaus more quickly.
# Example (Conceptual): Imagine a ball rolling down a hill. Momentum gives the ball inertia, allowing it to continue rolling even when it encounters small bumps or flat areas.
# 3. AdaGrad (Adaptive Gradient)

# AdaGrad adapts the learning rate for each parameter individually based on the past gradients. Parameters that have received large gradients in the past have their learning rates decreased, while parameters that have received small gradients have their learning rates increased.

# How it works: AdaGrad accumulates the sum of squared gradients for each parameter. The learning rate for each parameter is then divided by the square root of this accumulated sum.
# Benefit: Suitable for sparse data, where some features are infrequent.
# Drawback: The accumulated sum can become very large, causing the learning rate to become very small and the optimization to slow down significantly.
# 4. RMSprop (Root Mean Square Propagation)

# RMSprop is an improvement over AdaGrad that addresses the problem of the learning rate becoming too small. It uses an exponentially decaying average of squared gradients instead of accumulating all past squared gradients.

# How it works: RMSprop maintains a moving average of the squared gradients. This prevents the learning rate from decreasing too rapidly.
# Benefit: Often performs well in practice and is a good default choice for many problems.
# 5. Adam (Adaptive Moment Estimation)

# Adam combines the ideas of momentum and RMSprop. It uses both an exponentially decaying average of past gradients (momentum) and an exponentially decaying average of past squared gradients (RMSprop).

# How it works: Adam computes adaptive learning rates for each parameter. It maintains two moving averages: one for the gradients and one for the squared gradients.
# Benefit: Generally performs very well across a wide range of problems and is often the preferred optimizer.
# Example (Conceptual comparison):

# Imagine you're trying to find the bottom of a bowl.

# GD: You take small steps downhill, but it might take a long time to reach the bottom.
# Momentum: You gain speed as you go down, helping you to reach the bottom faster and overcome small bumps.
# AdaGrad: You take larger steps at the beginning and smaller steps as you get closer to the bottom, but you might get stuck if the slope becomes very gentle.
# RMSprop: Similar to AdaGrad, but you don't slow down as much, allowing you to reach the bottom more efficiently.
# Adam: Combines the best of both worlds, using momentum to accelerate and adaptive learning rates to fine-tune the search.

In [ ]:
#17. What is sklearn.linear_model ?
# sklearn.linear_model is a module in the scikit-learn (sklearn) library in Python that implements various linear models for regression and classification.
# Linear models assume a linear relationship between the input features and the target variable. While this might seem like a restrictive assumption, linear
# models are surprisingly effective for many real-world problems, especially as a first approach or when dealing with high-dimensional data. They are also
# computationally efficient and easy to interpret.

In [ ]:
#18. What does model.fit() do? What arguments must be given?
# The model.fit() method in scikit-learn is a crucial function used to train a machine learning model on your data. It's where the magic happens – the model
#learns the underlying patterns and relationships in your training data to make predictions on unseen data.

# What model.fit() Does:

# Processes Training Data: It takes two main arguments:
# X: This is your feature matrix, a two-dimensional array where each row represents a data sample and each column represents a feature (variable) used for
#prediction.
# y: This is your target vector, a one-dimensional array containing the labels (values to be predicted) for each data sample in X.
# Learns Model Parameters: Based on the chosen machine learning algorithm, fit() estimates the model's parameters (e.g., weights, biases in a neural network)
#that minimize a loss function. The loss function measures how well the model's predictions deviate from the actual target values.
# Internal Adjustments: The specific operations within fit() vary depending on the chosen model. However, they all involve iteratively adjusting the model's
#internal parameters to improve its performance on the training data.
# Required Arguments:

# X (feature matrix): This is always mandatory. It provides the data the model learns from.
# y (target vector): This is mandatory for supervised learning tasks (classification, regression). It provides the target values the model tries to predict.
#Unsupervised learning models might not require y.

In [10]:
#19. What does model.predict() do? What arguments must be given?
# The model.predict() method in scikit-learn is used to generate predictions using a trained machine learning model. After you've trained your model using model.fit(), you use model.predict() to apply that learned knowledge to new, unseen data.

# What model.predict() Does:

# Takes Input Data: It takes one main argument:
# X: This is the feature matrix of the new data for which you want to make predictions. It has the same format as the X you used in model.fit() (a two-dimensional array where each row is a sample and each column is a feature).
# Applies Learned Patterns: The predict() method uses the internal parameters learned during the fit() stage to make predictions based on the input data X.
# Returns Predictions: It returns a one-dimensional array containing the predicted values for each sample in X. The type of prediction depends on the model:
# Classification: Returns the predicted class labels (e.g., 0, 1, 2 for different categories).
# Regression: Returns the predicted numerical values.

In [11]:
#20. What are continuous and categorical variables?

# continuous variables are those variables that are in a given range. It can often be in decimal and fractional values. eg. height, weight, time, temperature etc
# Categorical variables are variable that are in object or string type. They are non numeric. Eg. color, blood group, education level etc

In [12]:
#21. What is feature scaling? How does it help in Machine Learning?
# Feature scaling is a technique used to standardize or normalize the range of independent variables or features of data. In other words, it transforms the
# features so that they have similar scales. This is important because features with larger values can dominate the learning process of some machine learning
# algorithms, leading to biased or suboptimal models.

In [16]:
#22. How do we perform scaling in Python?
from sklearn.preprocessing import StandardScaler
import numpy as np

# Sample data (replace with your actual data)
data = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])

# Create a StandardScaler object
scaler = StandardScaler()

# Fit the scaler to the data (calculates mean and standard deviation)
scaler.fit(data)

# Transform the data (applies the scaling)
scaled_data = scaler.transform(data)

# Combine fit and transform in one step
scaled_data_fit_transform = scaler.fit_transform(data)

print("Scaled Data:\n", scaled_data)
print("\nScaled Data Fit Transform:\n", scaled_data_fit_transform)

# Inverse transform (optional: to get back the original data)
original_data = scaler.inverse_transform(scaled_data)
print("\nOriginal Data:\n", original_data)

#Accessing mean and standard deviation
print("\nMean of each feature:\n", scaler.mean_)
print("\nStandard Deviation of each feature:\n", scaler.scale_)

from sklearn.preprocessing import MinMaxScaler
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])

scaler = MinMaxScaler(feature_range=(0, 1)) #Default range is 0 to 1
scaler.fit(data)
scaled_data = scaler.transform(data)

print("Scaled Data:\n", scaled_data)

original_data = scaler.inverse_transform(scaled_data)
print("\nOriginal Data:\n", original_data)

from sklearn.preprocessing import RobustScaler
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 600], [7, 8], [9, 10]]) #Outlier present

scaler = RobustScaler()
scaler.fit(data)
scaled_data = scaler.transform(data)

print("Scaled Data:\n", scaled_data)

original_data = scaler.inverse_transform(scaled_data)
print("\nOriginal Data:\n", original_data)

from sklearn.model_selection import train_test_split

X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
y = np.array([0, 1, 0, 1, 0])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train) #Fit and transform on training data
X_test_scaled = scaler.transform(X_test) #Transform on testing data with fitted scaler

print("X_train_scaled:\n", X_train_scaled)
print("\nX_test_scaled:\n", X_test_scaled)

Scaled Data:
 [[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]

Scaled Data Fit Transform:
 [[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]

Original Data:
 [[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]]

Mean of each feature:
 [5. 6.]

Standard Deviation of each feature:
 [2.82842712 2.82842712]
Scaled Data:
 [[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [0.75 0.75]
 [1.   1.  ]]

Original Data:
 [[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]]
Scaled Data:
 [[-1.         -1.        ]
 [-0.5        -0.66666667]
 [ 0.         98.66666667]
 [ 0.5         0.        ]
 [ 1.          0.33333333]]

Original Data:
 [[  1.   2.]
 [  3.   4.]
 [  5. 600.]
 [  7.   8.]
 [  9.  10.]]
X_train_scaled:
 [[ 1.18321596  1.18321596]
 [-0.16903085 -0.16903085]
 [-1.52127766 -1.52127766]
 [ 0.50709255  0.50709255]]

X_tes

In [18]:
#23. What is sklearn.preprocessing?
# sklearn.preprocessing is a module of scikit-learn (sklearn) library in python that provides a variety of tools for preprocesssing data before it is used
# for Machine Learning Models.
#key features of sklearn.preprocessing
#Standard(scaling) - This standardizes the features by removing the mean and scaling to unit variance(mean=0, std=1)
#Normalization - Normalizes samples individually to have unit norm.
#Encoding Categorical features - One Hot Encoding, Label encoder, Ordinal encoder

In [17]:
#24. How do we split data for model fitting (training and testing) in Python?
# from sklearn.model_selection import train_test_split;
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42);

In [19]:
#25.Explain data encoding?
#Data encoding is the process of converting data from one format to another, typically to make it suitable for machine learning algorithms. Many machine
#learning algorithms work best with numerical input, so encoding is often necessary to transform categorical data (text, labels, etc.) into numerical
#representations.